# Generated by Django 2.1.7 on 2019-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
