# Generated by Django 2.1.7 on 2019-03-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("rippy", "0002_job_path")]

    operations = [
        migrations.AlterModelOptions(name="job", options={"ordering": ["-id"]})
    ]
