# Generated by Django 2.1.7 on 2019-03-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("rippy", "0003_auto_20190310_1858")]

    operations = [
        migrations.RenameField(
            model_name="job", old_name="last_update", new_name="last_updated"
        )
    ]
