# Generated by Django 2.1.7 on 2019-03-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rippy", "0004_auto_20190310_1858")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("parsing", "Parsing"),
                    ("downloading", "Downloading"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("waiting", "Waiting for user-input"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
