# Generated by Django 2.1.7 on 2019-03-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippy', '0005_auto_20190311_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=5000),
        ),
    ]
