# Generated by Django 2.1.7 on 2019-07-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippy', '0007_job_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scheduled',
            field=models.BooleanField(default=True),
        ),
    ]
